version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    ports:
      - "3881:8000"
    env_file:
      - .env
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - db

  db:
    image: influxdb:2.6-alpine
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdbv2_data:/var/lib/influxdb2
      - influxdbv2_config:/etc/influxdb2
      - ./db/pat.csv:/home/influxdb/pat.csv
      - ./db/EAT.csv:/home/influxdb/EAT.csv
    command:
      - bash -c "influx write --bucket my-bucket --format=csv --file /home/influxdb/pat.csv && influx write --bucket my-bucket --format=csv --file /home/influxdb/EAT.csv"

  telegraf:
    image: telegraf:1.19
    volumes:
      - ./docker/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - .env
    depends_on:
      - db

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker/mosquitto/pwfile:/mosquitto/config/pwfile
      - mqtt_data:/mosquitto/data:rw
      - mqtt_log:/mosquitto/log:rw
    restart: unless-stopped

volumes:
  influxdbv2_data:
    driver: local
  influxdbv2_config:
    driver: local
  mqtt_data:
    driver: local
  mqtt_log:
    driver: local
