version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/var/www/html/src
      - ./frontend/static:/var/www/html/static
      - ./frontend/vite.config.js:/var/www/html/vite.config.js
      - ./frontend/postcss.config.js:/var/www/html/postcss.config.js
      - ./frontend/svelte.config.js:/var/www/html/svelte.config.js
      - ./frontend/tailwind.config.js:/var/www/html/tailwind.config.js
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
