version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/var/www/html/src
      - ./frontend/static:/var/www/html/static
      - ./frontend/vite.config.js:/var/www/html/vite.config.js
      - ./frontend/postcss.config.js:/var/www/html/postcss.config.js
      - ./frontend/svelte.config.js:/var/www/html/svelte.config.js
      - ./frontend/tailwind.config.js:/var/www/html/tailwind.config.js
    ports:
      - 3000:3000
    env_file:
      - .env
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  db:
    image: influxdb:2.6-alpine
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdbv2_data:/var/lib/influxdb2
      - influxdbv2_config:/etc/influxdb2
      - ./db/pat.csv:/home/influxdb/pat.csv
      - ./db/EAT.csv:/home/influxdb/EAT.csv

  telegraf:
    image: telegraf:1.19
    volumes:
      - ./docker/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - .env
    depends_on:
      - db

volumes:
  influxdbv2_data:
    driver: local
  influxdbv2_config:
    driver: local
