name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "${{ secrets.ENV_FILE }}" > .env && make build
      
  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Run the Docker image
      run: make up
